### ISSUE TITLE
Compilation time performance for large family of case classes

### ISSUE THREAD

**Issue by gabro** [fommil/spray-json-shapeless#13]
I've read about the quadratic performance degradation of the compilation time mentioned in the scaladoc. Yet, I thought it was fixed by https://github.com/milessabin/shapeless/commit/d4c3c71933e8c4ab6bc1fcde17e92961f9c0f897 as outcome of the discussion in https://github.com/milessabin/shapeless/issues/381.

Apparently this isn't the case, since I can still observe what looks like a quadratic increase when adding new cases to an ADT.

Am I missing something?

**Comment by milessabin** [comment]
Are you sure that you're working with a sufficiently recent version of shapeless that has that fix? If you are, can you put together a simple reproduction?

**Comment by gabro** [comment]
I'm on 2.3.0-SNAPSHOT but it's a rather complex project, so it might be something else. I'll put together a simple example.

**Comment by gabro** [comment]
I tried to isolate it and I couldn't. There's something wrong with my (rather big) project, so I'm closing this now.
Thanks for the quick support
