### ISSUE TITLE
Replace global variant of Strict with Cached

### ISSUE THREAD

**Issue by federico-pellegatta** [fommil/spray-json-shapeless#14]
1.2.0-SNAPSHOT does not compile anymore after https://github.com/milessabin/shapeless/commit/24d9d2e42c54a57a7999c4acdef49e982c9620a4

**Comment by fommil** [comment]
@alexarchambault help!

Also, I'd like to chat with you (gitter?) about your changes an I really need to understand them for my scalax workshop in 6 weeks.

**Comment by alexarchambault** [comment]
@fommil Sure, I'm a bit busy right now, but I can totally find time for that by the end of the month.

**Comment by alexarchambault** [comment]
About the changes of https://github.com/milessabin/shapeless/commit/24d9d2e42c54a57a7999c4acdef49e982c9620a4, it's just that `Lazy.Global[T]` and `Strict.Global[T]` should be substituted by `Cached[Lazy[T]]` and `Cached[Strict[T]]`.

**Comment by fommil** [comment]
:smile:

**Comment by federico-pellegatta** [comment]
I have already tried that trivial solution, the outcome was the following:
```
java.lang.IllegalArgumentException: Could not find proxy for val fresh$macro$64: fommil.sjs.LowPriorityFamilyFormats#WrappedRootJsonFormat in List(value fresh$macro$64, method apply$mcV$sp, <$anon: Function0>, class FamilyFormatsSpec, package sjs, package fommil, package <root>) (currentOwner= method apply )
```

**Comment by alexarchambault** [comment]
FYI, I was able to reproduce that in projects of mine, and fix it too. I'll send a PR with a fix in shapeless, tomorrow I think.
