### ISSUE TITLE
Support of annotations on the case class for the customisation rules

### ISSUE THREAD

**Issue by joan38** [fommil/spray-json-shapeless#15]
So for example have:

```
@SprayJson(hintKey = "hint")
sealed trait SubTrait extends SimpleTrait
```

**Comment by fommil** [comment]
I've heard from quite a few people wanting something like this (even though it pollutes the clean domain model with serialisation information). I think we can support it via a macro that expands the annotation into the required implicit that we need. e.g. in this case a `CoproductHint[SubTrait]`.

**Comment by fommil** [comment]
would be cool, but I think we want to be implicit driven. Have a look at https://github.com/fommil/scala-data-classes for annotation driven ways of generating things (for ideas)
