### ISSUE TITLE
Use with generics and reflection

### ISSUE THREAD

**Issue by cory-p-oncota** [fommil/spray-json-shapeless#18]
I'm not sure if this is an enhancement request or I am missing an approach in which to achieve this.

I have many of the following case classes, which are generated code using a trait dependent on reflection:
```scala
case class Foo(f: String) with Printer
case class Bar(b: Int) with Printer
```

In reality, this trait is responsible for automatically generating REST calls and, thus, needs to marshall or unmarshall the response. To simplify I simply define it to print and "unprint":
```scala
import fommil.sjs.FamilyFormats._

trait Printer[C <: Printer[C]] {
  import scala.reflect.runtime.{universe => ru}
  import scala.reflect.runtime.universe._

  import scala.concurrent.ExecutionContext.Implicits.global

  def print(entity: C)(implicit tag: TypeTag[C]): Future[String] = {
    Future { entity.toJson.compactPrint }
  }

  def unprint(json: String)(implicit tag: TypeTag[C]): Future[C] = {
    Future { json.parseJson.convertTo[C] }
  }
}
```

However, I am receiving the typical spray-json error:
```
Cannot find JsonReader or JsonFormat type class for C
```

Am I attempting to perform an act unsupported by the library or approaching this in the incorrect manner?

**Comment by fommil** [comment]
you shouldn't be using runtime reflection at all, the point of this library is to avoid that. If you'd like to learn more about how it works, please watch https://github.com/fommil/shapeless-for-mortals if you'd just like to use the library, I recommend reading and understanding the test cases. The `milessabin/shapeless` channel on gitter might be a better place to ask more questions.
