### ISSUE TITLE
Support of Inheritance

### ISSUE THREAD

**Issue by quaddef** [fommil/spray-json-shapeless#21]
Hi, does your framework supports inheritance or mix-in?
I can't see fields from parents of my class in output.

**Comment by fommil** [comment]
please read the documentation. This is on the front of the README.

**Comment by quaddef** [comment]
I've read documentation, it doesn't have examples with trait, which have variables. 

In output I've got only "type": "JsObject", my entity fields, and nothing about trait fields. So, cause of that, I've opened issue.

**Comment by fommil** [comment]
traits shouldn't have variables.

**Comment by quaddef** [comment]
Ok, what about superclasses?

**Comment by fommil** [comment]
spray-json-shapeless only supports Algebraic Data Types, if you want to write java style code in scala then you would be best using a java library to support your style. Please read the documentation at typelevel.org on how to write scala using a functional programming style.
