### ISSUE TITLE
Enhancement: support shapeless records and possibly unions

### ISSUE THREAD

**Issue by m50d** [fommil/spray-json-shapeless#28]
Shapeless offers record and union formats that are irritatingly almost-but-not-quite compatible with the product/coproduct representation of case classes and sealed traits (the difference being whether the singleton-typed labels are `Symbol`s or `String`s). These records are a good fit for JSON for many purposes (e.g. returning a subset of the fields of an object) and at interface level seem like something a spray-json-shapeless project should offer.

In practice a common implementation is awkward. In particular it's not clear how to hook up the `ProductHint` mechanism, because there is no "outer" type - a record has a type that looks like `FieldType[..., ...] :: FieldType[..., ...] :: ... :: HNil`. I could write (and in fact have written) an implementation that supports records but has no way to adjust the null-handling setting, but would that be too misleading for library users? Or is there some clever way to permit the hinting mechanism to work?

**Comment by danslapman** [comment]
I offer support for such types in my https://github.com/danslapman/shapeless-play-json library, this approach can be easily adapted for spray-json.

**Comment by fommil** [comment]
hmm, not sure I'm particularly keen on the license @danslapman 

The FSF recommendation at https://www.gnu.org/licenses/license-list.en.html is 

> We do not recommend this license. If you want a lax permissive license for a small program, we recommend the X11 license. A larger program usually ought to be copyleft; but if you are set on using a lax permissive license for one, we recommend the Apache 2.0 license since it protects users from patent treachery.

**Comment by danslapman** [comment]
@fommil if I implement extensible records support as a PR for Your library by myself, will it be ok?)

**Comment by fommil** [comment]
@danslapman yes, that'd be great! But you'll need to contribute under the terms of the Apache 2.0.

**Comment by danslapman** [comment]
@fommil surely! Then, I will do it shortly.

**Comment by fommil** [comment]
@m50d is this completed now? I was just going to cut a 1.4.0 today

**Comment by m50d** [comment]
Yep the PR went in - it wasn't mine, can't remember immediately.

**Comment by fommil** [comment]
I just released 1.4.0 (and removed this lib from typelevel because I recommend circe instead)
