### ISSUE TITLE
Ambiguous implicit values JsValueFormat and method familyFormat

### ISSUE THREAD

**Issue by savulchik** [fommil/spray-json-shapeless#33]
I would like to report the problem I discovered when using the library to derive `JsonFormat` for a case class containing `JsValue` field. The following example compiles with ambiguous implicit values error:
```scala
import spray.json._
import fommil.sjs._

case class Foo(bar: JsValue)

object Test {
  import FamilyFormats._
  val foo: Foo = ??? 
  foo.toJson
}
```
```
[error] /home/s.savulchik/projects/spray-json-shapeless-troubles/Test.scala:9: ambiguous implicit values:
[error]  both object JsValueFormat in trait AdditionalFormats of type fommil.sjs.FamilyFormats.JsValueFormat.type
[error]  and method familyFormat in trait LowPriorityFamilyFormats of type [T, Repr](implicit gen: shapeless.LabelledGeneric.Aux[T,Repr], implicit sg: shapeless.Cached[shapeless.Strict[fommil.sjs.FamilyFormats.WrappedRootJsonFormat[T,Repr]]], implicit tpe: shapeless.Typeable[T])spray.json.RootJsonFormat[T]
[error]  match expected type spray.json.JsonFormat[spray.json.JsValue]
[error]   foo.toJson
[error]       ^
```
It seems like the workaround is to define an explicit `JsonFormat` for such a case class:
```scala
import spray.json._
import fommil.sjs._

case class Foo(bar: JsValue)

object JsonProtocol extends DefaultJsonProtocol with FamilyFormats {
  implicit object FooFormat extends JsonFormat[Foo] {
    def write(foo: Foo) = ???
    def read(json: JsValue) = ???
  }
} 

object Test {
  import JsonProtocol._
  val foo: Foo = ???
  foo.toJson
}
```
If such a case class is part of a sealed family then I have to define an explicit `JsonFormat` for the family type and not just for the offending case class.

**Comment by fommil** [comment]
you're probably experiencing problems because your case class is in a parent package of where you derive it. Can you try putting the protocol and case classes in sibling packages? (Please read the docs on JsonFormat about this)

**Comment by savulchik** [comment]
I have already tried sibling packages - the problem persists (see https://github.com/savulchik/spray-json-shapeless-troubles/blob/master/SiblingPackagesTest.scala). I guess there are two factors that account for the problem:
1. `JsValue` is a sealed family so `familyFormat` method is eligible from the compiler point of view
2. both `familyFormat` method and `JsValueFormat` object have the same precedence during resolution of implicits in scope by the compiler (not sure how to verify this)

**Comment by fommil** [comment]
I guess it's kinda weird that you'd want to allow arbitrary json in a case class, but I guess that's what you need to do. Your workaround sounds reasonable, although it's probably possible to do it in less lines of code by fiddling with precedence rules.
